### ISSUE TITLE
Move shared documentation into x-common

### ISSUE THREAD

**Issue by kytrinyx** [exercism/rossconf#10]
Goal: https://github.com/exercism/rossconf/issues/11

-------------

**Skillsets:** Organizing information? Metadata? Mindmaps? Moving text files around? This one could be as simple as just moving files around, but is worth thinking about in a larger context.

-------

**TODO**

Create a `docs/` directory in the x-common repository under [`app/pages`](https://github.com/exercism/docs/tree/master/app/pages), and move content from `contributing`, `process` and `topics` into that repository.

I don't know what sort of structure would make sense for this yet. Perhaps for now each markdown file should simply be put straight into the `docs/` repository, and maybe we should have a `config.json` or `config.yaml` file to keep metadata in (grouping things into themes, ordering things).

This is going to be served up as JSON by the x-api application in order to be able to provide the information from within the exercism app.

Perhaps there's a first step before actually moving the content, consisting of making a suggestion about how to best organize this, but I would settle for just sticking everything in one folder and either having a config or having some metadata at the top to identify topic/ordering).

**Comment by studiolo** [comment]
Hi, I'd like to do this. I'm a documentation person :-) And this looks like a clearly defined task.

**Comment by kytrinyx** [comment]
Sweet, thanks!

**Comment by kytrinyx** [comment]
There might be stuff in https://github.com/exercism/exercism.io/blob/master/README.md that could be better in the new docs stuff.

Also, perhaps https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md
