### ISSUE TITLE
Test suite "show" page assumes only one test file

### ISSUE THREAD

**Issue by kytrinyx** [exercism/rossconf#19]
**Problem:** We have a page that lists the test suite for a problem in a given language, and that page assumes that there is only one test suite. Some languages have helper files that are a part of the test suite.

**Solution:** Get all of the test files in a loop instead of just getting one.

**Skillset:** A bit of Ruby. It's all in one place in one file, though, so this is quite beginner-friendly.

The file is: `lib/app/routes/metadata.rb`, and it's the first endpoint: `get '/exercises/:track_id/:slug'`.

It doesn't look like we have a test for this, so a bonus task (not required) would be to add a test, stubbing out the `Xapi` call. There are other tests that do this, so it should be possible to find something similar for inspiration.

https://github.com/exercism/exercism.io/issues/2273

**Comment by andis** [comment]
I’ll take it

**Comment by kytrinyx** [comment]
Fixed in exercism/exercism.io#2396
