### ISSUE TITLE
Add shared metadata for hello-world problems

### ISSUE THREAD

**Issue by kytrinyx** [exercism/rossconf#4]
Goal: https://github.com/exercism/rossconf/issues/12

-------------

**Skillset:** Ability to explain stuff in English, basic understanding of how exercism works.

-------------

Each language has their own test suite, but the README and other metadata is shared. We need to add the shared metadata for the hello world problem to https://github.com/exercism/x-common

The following files need to be added:

- `hello-world.md` - what will become the shared README across all language tracks.
- `hello-world.yml` - a short description of the problem, which will be used on the exercism website when showing lists of the problems available in each track.

**Comment by ramonh** [comment]
Hiya! I'll have a go at this.

**Comment by kytrinyx** [comment]
w00t :)

**Comment by kytrinyx** [comment]
Fixed in exercism/x-common#77
